#!/usr/bin/env bash
CURRENT_DIR=$(dirname $(readlink -f "$0"))
uname -m | grep x86_64 > /dev/null 2>&1
if [ $? -eq 0 ]; then
    ${CURRENT_DIR}/7z_x86/7zzs $@
else
    ${CURRENT_DIR}/7z_arm/7zzs $@
fi
