#!/usr/bin/env bash
CURRENT_DIR=$(dirname $(readlink -f "$0"))
uname -m | grep x86_64 > /dev/null 2>&1
if [ $? -eq 0 ]; then
    ${CURRENT_DIR}/fio_x86/fio $@
else
    ${CURRENT_DIR}/fio_arm/fio $@
fi
